services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - cloud-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 26102005
      MYSQL_DATABASE: cloud_optimizer
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cloud-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p26102005 --silent"]
      interval: 5s
      timeout: 5s
      retries: 30

  metrics-collector-service:
    build: ./metrics-collector-service
    container_name: metrics-collector-service
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/cloud_optimizer
    networks:
      - cloud-network

  usage-analysis-service:
    build: ./usage-analysis-service
    container_name: usage-analysis-service
    depends_on:
      - mongodb
      - mysql
    environment:
      MONGO_URI: mongodb://mongodb:27017/
      MYSQL_URI: mysql+pymysql://root:26102005@mysql:3306/cloud_optimizer
    networks:
      - cloud-network

  optimization-engine:
    build: ./optimization-engine
    container_name: optimization-engine
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cloud_optimizer?createDatabaseIfNotExist=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 26102005
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
    networks:
      - cloud-network
    restart: on-failure

  cost-simulation-service:
    build: ./cost-simulation-service
    container_name: cost-simulation-service
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cloud_optimizer?createDatabaseIfNotExist=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 26102005
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - cloud-network

  alert-service:
    build: ./alert-service
    container_name: alert-service
    ports:
      - "8084:8084"
    networks:
      - cloud-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - metrics-collector-service
      - optimization-engine
      - cost-simulation-service
      - alert-service
    networks:
      - cloud-network

networks:
  cloud-network:
    driver: bridge

volumes:
  mongo_data:
  mysql_data:
