spring:
  datasource:
    url: jdbc:mysql://mysql:3306/cloud_optimizer?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: 26102005
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: alert-service

server:
  port: 8084
